apiVersion: v1
kind: Service
metadata:
  name:  authservice-svc
  labels:
    app: authservice
spec:
  selector:
    app:  authservice
  type: NodePort
  ports:
   - port:  3000
     nodePort: 30002
     protocol: TCP