apiVersion: v1
kind: ReplicationController
metadata:
  name: authservice-rc
spec:
  replicas: 5
  selector:
    app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: hello-ctr
          image: vinitkumargoel/lbgpoc_authservice:latest
          ports:
            - containerPort: 3000